fullnameOverride: ""

ingress:
  className: "nginx"
  host: "monitoring.local"
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  services:
    - path: /grafana
      name: grafana
      backend:
        service:
          name: monitoring-grafana
          port: 80
    - path: /prometheus
      name: prometheus
      backend:
        service:
          name: monitoring-prometheus-server
          port: 80
    - path: /elasticsearch
      name: elasticsearch
      backend:
        service:
          name: elasticsearch-master
          port: 9200
    - path: /alertmanager
      name: alertmanager
      backend:
        service:
          name: monitoring-prometheus-alertmanager
          port: 80

prometheus:
  serverFiles:
    prometheus.yml:
      scrape_configs:
        - job_name: "kubernetes-services"
          kubernetes_sd_configs:
            - role: service

elasticsearch:
  replicas: 1
  minimumMasterNodes: 1

prometheus-elasticsearch-exporter:
  es:
    uri: http://elasticsearch-master:9200
