fullnameOverride: ""

ingress:
  className: "nginx"
  host: "monitoring.local"
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  services:
    - name: grafana
      backend:
        service:
          name: monitoring-grafana
          port: 80
    - name: prometheus
      backend:
        service:
          name: monitoring-prometheus-server
          port: 80
    - name: elasticsearch
      backend:
        service:
          name: elasticsearch-master
          port: 9200
    - name: alertmanager
      backend:
        service:
          name: monitoring-prometheus-alertmanager
          port: 80

prometheus:
  serverFiles:
    prometheus.yml:
      scrape_configs:
        - job_name: "kubernetes-services"
          kubernetes_sd_configs:
            - role: service
          relabel_configs:
            - source_labels:
                [__meta_kubernetes_service_annotation_prometheus_io_scrape]
              action: keep
              regex: true
            - source_labels:
                [__meta_kubernetes_service_annotation_prometheus_io_path]
              action: replace
              target_label: __metrics_path__
              regex: (.+)
            - action: labelmap
              regex: __meta_kubernetes_service_label_(.+)
            - source_labels: [__meta_kubernetes_namespace]
              action: replace
              target_label: kubernetes_namespace
            - source_labels: [__meta_kubernetes_service_name]
              action: replace
              target_label: kubernetes_name

elasticsearch:
  replicas: 1
  minimumMasterNodes: 1

prometheus-elasticsearch-exporter:
  service:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: /metrics
  es:
    uri: http://elasticsearch-master:9200
